"""Regenerate local font assets; requires fonttools[woff] (not needed to build).

Run from the repository root after npm install. Full Font Awesome faces remain
available as fallbacks, so icons introduced later continue to work immediately.
"""

import re
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONT_AWESOME = ROOT / "node_modules/@fortawesome/fontawesome-free"
FONTS = ROOT / "app/fonts"

for source in FONTS.glob("*.woff"):
    font = TTFont(source, recalcTimestamp=False)
    font.flavor = "woff2"
    target = source.with_suffix(".woff2")
    font.save(target)
    print(f"{source.name}: {source.stat().st_size} -> {target.stat().st_size} bytes")

    # Ship common Latin text first; the complete face remains a CSS fallback
    # for every other character supported by the supplied font.
    latin = TTFont(source, recalcTimestamp=False)
    options = subset.Options()
    options.name_IDs = ["*"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=(
        set(range(0x20, 0x100)) | set(range(0x2000, 0x2070)) |
        set(range(0x20A0, 0x20D0)) | {0x2122} | set(range(0x2190, 0x2200))
    ))
    subsetter.subset(latin)
    variant = source.stem.split("-")[-1]
    for record in latin["name"].names:
        value = {1: "Flexy UI Text", 2: variant, 3: f"FlexyUIText-{variant}-Latin",
                 4: f"Flexy UI Text {variant}", 6: f"FlexyUIText-{variant}",
                 16: "Flexy UI Text", 17: variant}.get(record.nameID)
        if value:
            record.string = value.encode(record.getEncoding())
    latin.flavor = "woff2"
    latin_target = source.with_suffix(".latin.woff2")
    latin.save(latin_target)
    print(f"{latin_target.name}: {latin_target.stat().st_size} bytes")

icon_names = {"fa-caret-up", "fa-caret-down"}
for folder in ("app", "components"):
    for source in (ROOT / folder).rglob("*.tsx"):
        icon_names.update(re.findall(r"\bfa-[a-z0-9]+(?:-[a-z0-9]+)*", source.read_text(encoding="utf-8")))

css = (FONT_AWESOME / "css/all.css").read_text(encoding="utf-8")
unicodes = set()
for selectors, value in re.findall(r"([^{}]+)\{\s*content:\s*\"\\([a-f0-9]+)\";?\s*\}", css):
    if icon_names.intersection(re.findall(r"\.([a-z0-9-]+)::?before", selectors)):
        unicodes.add(int(value, 16))

output = [
    "/* Generated by scripts/subset-fonts.py. Font Awesome Free 6.4.0",
    " * Copyright 2023 Fonticons, Inc. Fonts: SIL OFL 1.1.",
    " * Full local faces are imported first; these ranges use smaller subsets.",
    " * https://fontawesome.com/license/free */",
]
for name, family, weight in (
    ("solid-900", "Font Awesome 6 Free", 900),
    ("regular-400", "Font Awesome 6 Free", 400),
    ("brands-400", "Font Awesome 6 Brands", 400),
):
    font = TTFont(FONT_AWESOME / f"webfonts/fa-{name}.ttf", recalcTimestamp=False)
    selected = unicodes.intersection(font.getBestCmap())
    if not selected:
        continue
    options = subset.Options()
    options.flavor = "woff2"
    options.name_IDs = ["*"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=selected)
    subsetter.subset(font)
    # These modified fonts use their own primary names under SIL OFL. The CSS
    # family remains a compatibility alias for existing Font Awesome classes.
    variant = name.split("-")[0].title()
    names = {
        1: "Flexy UI Icons",
        2: variant,
        3: f"FlexyUIIcons-{variant}-6.4.0-Subset",
        4: f"Flexy UI Icons {variant}",
        6: f"FlexyUIIcons-{variant}",
        16: "Flexy UI Icons",
        17: variant,
    }
    for record in font["name"].names:
        if record.nameID in names:
            record.string = names[record.nameID].encode(record.getEncoding())
    font.flavor = "woff2"
    target = FONTS / f"fa-{name}-subset.woff2"
    font.save(target)
    ranges = ", ".join(f"U+{code:X}" for code in sorted(selected))
    output.append(f"""@font-face {{
  font-family: '{family}';
  font-style: normal;
  font-weight: {weight};
  font-display: swap;
  src: url('./fonts/{target.name}') format('woff2');
  unicode-range: {ranges};
}}""")
    print(f"{target.name}: {len(selected)} codepoints, {target.stat().st_size} bytes")

(ROOT / "app/icon-fonts.css").write_text("\n".join(output) + "\n", encoding="utf-8")
(FONTS / "Font-Awesome-LICENSE.txt").write_bytes((FONT_AWESOME / "LICENSE.txt").read_bytes())
